### PR TITLE
fix: breaking change output of store import cmd

### LINKED ISSUE #354: fga store create - breaking change v0.5
We currently parse the response from `fga store create --model Model.fga` with `jq` to set environment variables with store and model ids as per this documented example: https://github.com/openfga/cli?tab=readme-ov-file#response-1

I'm not sure if it is the progress bar itself or the additional `✅ Store imported` line before the json, but this has broken our CICD process. Full response:

```
✅ Store imported                                                                                                                                                                                                                                                                                
{
  "store": {
    "created_at":"2024-06-24T20:24:54.656783Z",
    "id":"01J15YRJ.....WKRHRC957",
    "name":"some_name",
    "updated_at":"2024-06-24T20:24:54.656783Z"
  },
  "model": {
    "authorization_model_id":"01J15YR.......EFSJN4TD03"
  }
}
```

Error:
`jq: parse error: Invalid numeric literal at line 1, column 11`

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## References

fixes #354

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by ewanharris** [comment]
@Siddhant-K-code, thanks for providing the PR! From testing as the progressbar still writes to stdout piping to jq still doesn't work.

What do you think about adding `progressbar.OptionSetWriter(os.Stderr),` to the options passed to `progressbar.NewOptions`. I think we're fine to pipe to stderr as it's deemed suitable for error messages **and diagnostics**. With that change the progress bar is displayed while importing tuples and I'm able to pipe to jq sucessfully

```
fga store import --file ./example/model.fga.yaml | jq  .store.id
"01J17BR1JA0G70FXMFFKMJ6ZRA"
```

**Comment by Siddhant-K-code** [comment]
@ewanharris, Just did that in [`2d81b67`](https://github.com/openfga/cli/pull/355/commits/2d81b67cfaf4acebadd6aa7b95b8a4171145d9ba), it should be fine now 🤞🏼

File: cmd/store/import.go [hunk 1]
```diff
@@ -183,8 +184,6 @@ func importStore(
 		return nil, fmt.Errorf("failed to finish progress bar: %w", err)
 	}
 
-	fmt.Println("✅ Store imported")
-
```
Comment (Siddhant-K-code) [inline cmd/store/import.go:187]: Also, I think it's fine to remove this, because it might mis-lead in some cases where store are getting "created" and not "imported"

**Review by ewanharris — APPROVED** [review]
Test locally and this looks good to me, thanks for the quick PR @Siddhant-K-code!

Pinging @rhamzeh for a second 👀

**Comment by Siddhant-K-code** [comment]
Sure, and again sorry for that breaking change 🙈

**Review by rhamzeh — APPROVED** [review]
