### PR TITLE
fix: don't attempt to import tuples if none are present

### LINKED ISSUE #368: `store import` without tuples always fails
When using `store import` just for the model but without or with an empty `tuples` section, it always errors with:
`Error: failed to import store: failed to finish progress bar: max must be greater than 0`

From looking at the code, the model should've still been imported though, so just a surface thing.

### PR DESCRIPTION
**Pull request by ap0calypse8**
## References

Fixes #368

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

### CODE REVIEW

**Comment by ap0calypse8** [comment]
To summarize the changes: We added a check for len(storeData.Tuples) == 0 after initializing the FGA client. 2. If there are no tuples, we print a message and return the response immediately. The progress bar initialization and tuple import process only occur if there are tuples to import. This should resolve the issue you're experiencing while still allowing the model to be imported successfully

**Comment by ap0calypse8** [comment]
You can review and help me out with running the tests.

File: cmd/store/import.go [hunk 1]
```diff
@@ -116,30 +117,73 @@ func importStore(
...
-		response *CreateStoreAndModelResponse
-		err      error
-	)
+	response, err := createOrUpdateStore(clientConfig, fgaClient, storeData, format, storeID, fileName)
+	if err != nil {
+		return nil, err
+	}
 
+	if len(storeData.Tuples) == 0 {
+		fmt.Println("No tuples to import.")
```
Comment (ewanharris) [inline cmd/store/import.go:126]: We've had issues previously (#354) with folks relying on this command producing JSON parseable output. I think we should remove this log to avoid breaking that again.

**Review by ewanharris — CHANGES_REQUESTED** [review]

**Comment by ap0calypse8** [comment]
hey any update from the side of the reviewer?

**Review by ewanharris — APPROVED** [review]
Thanks @ap0calypse8!

**Comment by ap0calypse8** [comment]
you are welcome!
