### PR TITLE
fix: properly exit on errors

### LINKED ISSUE #62: CLI is appending the help message to errors
image

### PR DESCRIPTION
**Pull request by rhamzeh**
## Description

Screenshot 2023-07-07 at 9 05 51 PM

## References

closes #62 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: cmd/tuple/changes.go [hunk 1]
```diff
@@ -64,32 +64,27 @@ func readChanges(fgaClient client.SdkClient, maxPages int, selectedType string)
 
 // changesCmd represents the changes command.
 var changesCmd = &cobra.Command{
-	Use:   "changes",
-	Short: "Read Relationship Tuple Changes (Watch)",
+	Use:     "changes",
+	Short:   "Read Relationship Tuple Changes (Watch)",
+	Example: "fga tuple changes --store-id=01H0H015178Y2V4CX10C2KGHF4 document",
```
Comment (adriantam) [inline cmd/tuple/changes.go:69]: is this right?
Should it be 
```
fga tuple changes --store-id=01H0H015178Y2V4CX10C2KGHF4 --type=document
```

Also need to fix REAMDE

**Review by adriantam — CHANGES_REQUESTED** [review]

**Review by jpadilla — APPROVED** [review]

**Review by adriantam — APPROVED** [review]
