### PR TITLE
simplify err messages in check function

### LINKED ISSUE #404: inconsistent error message when Check fails
This is super minor, but:

```
[11/10/24 5:52:39] ~/GitHub/openfga-main/.demo (feat/access-control) $ fga --version
fga version v`0.6.1` (commit: `f47cb263d52f9e0751c40e74f983b567b4840133`, date: `2024-09-09T17:14:35Z`)
[11/10/24 5:53:57] ~/GitHub/openfga-main/.demo (feat/access-control) $ fga query check --config project.config.yaml --store-id="$PROJECT_STORE_ID" user:anne member organization:openfga

Using config file: project.config.yaml
Error: failed to check due to failed to check due to Check validation error for POST Check with body {"code":"latest_authorization_model_not_found","message":"No authorization models found for store '01J9YWE5HEDR3X0AABYFA8YAHD'"}
 with error code latest_authorization_model_not_found error message: No authorization models found for store '01J9YWE5HEDR3X0AABYFA8YAHD'
```

Notice how the error says

> Error: failed to check due to **failed to check due to** Check

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This pull request updates the error messages in the check function to provide more informative and concise error messages. The "failed to check" error message has been changed to "check failed" to better reflect the actual error.

Updated error message would look like:

> Error: check failed: <error_message>

Actual Example: 

> Error: check failed: Post "http://localhost:8080/stores/01H4P8Z95KTXXEP6Z03T75Q984/check": dial tcp [::1]:8080: connect: connection refused

## References

fixes #404

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

### CODE REVIEW

File: cmd/query/check.go [hunk 1]
```diff
@@ -53,7 +53,7 @@ func check(
 
 	response, err := fgaClient.Check(context.Background()).Body(*body).Options(*options).Execute()
 	if err != nil {
-		return nil, fmt.Errorf("failed to check due to %w", err)
+		return nil, fmt.Errorf("due to %w", err)
```
Comment (ewanharris) [inline cmd/query/check.go:56]: We currently prefer to prefix the message but it leads to situations like this issue where error messages become verbose and repeated.

I wonder if we could just return the `err` here directly rather than prefix the error? We could add `due to` on line 93, but maybe that's also a little verbose and we could just add `:`  so error messages are like  

`check failed: <error_message>`?
```suggestion
		return nil, err //nolint:wrapcheck
```

Comment (Siddhant-K-code) [reply cmd/query/check.go]: resolved in [5670b61](https://github.com/openfga/cli/pull/405/commits/5670b61ee201a7452073b65745548913ebad728a)

**Review by ewanharris — APPROVED** [review]
Thanks @Siddhant-K-code!
