### PR TITLE
fix: correct flag value type in delete, import, and write

### LINKED ISSUE #387: `fga tuple write` returns an error
It's not possible to use `fga tuple write` or `fga store import` as it displays the following error:

```
$ fga tuple write --file tuples.yaml 
Error: failed to parse max tuples per write: trying to get int32 value of flag of type int
```

### PR DESCRIPTION
**Pull request by ewanharris**
## Description

Overlooked the need to change the flag declaration as part of the refactoring here #382.

Will work on adding some integration tests to cover this.

## References

Fixes #387

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: cmd/tuple/import.go [hunk 1]
```diff
@@ -32,10 +32,10 @@ import (
 )
 
 // MaxTuplesPerWrite Limit the tuples in a single batch.
-var MaxTuplesPerWrite = 1
+var MaxTuplesPerWrite = int32(1)
 
 // MaxParallelRequests Limit the parallel writes to the API.
-var MaxParallelRequests = 10
+var MaxParallelRequests = int32(10) //nolint:mnd
```
Comment (stevehobbsdev) [inline cmd/tuple/import.go:38]: We didn't need `nolint:mnd` previously? Do we need it on line 35 as well?

**Review by rhamzeh — DISMISSED** [review]

File: cmd/tuple/import.go (hunk 1 above)
Comment (ewanharris) [reply cmd/tuple/import.go:38]: It seems that because `10` is an argument to the casting, that's what is triggering the check here. As for line 35 `1` is by [default excluded](https://github.com/tommy-muehle/go-mnd#excludes)

Good call out though as I think I can refactor this to drop the `int32` cast which means I can drop the lint

**Review by rhamzeh — APPROVED** [review]
